#!/usr/bin/env php
<?php
//error_reporting(E_ERROR | E_WARNING | E_PARSE);

/**
 * @author John Snook
 * @date May 8, 2018
 * @license https://snooky.biz/site/license
 * @copyright 2018 John Snook Consulting
 * Description of Tui
 */
//use Tui;
#use \johnsnook\tui\components\Program;
defined('TUI_DEBUG') or define('TUI_DEBUG', true);
spl_autoload_register(function($className) {
    //echo $className . PHP_EOL;

    $className = str_ireplace('tui\\', '', $className);
    $className = str_replace('\\', DIRECTORY_SEPARATOR, $className);
    include_once $className . '.php';
});
include_once 'Tui.php';
//print_r(get_declared_classes());

if (file_exists($argv[1])) {
    Tui::$program = require $argv[1];
    $exitCode = Tui::$program->run();
    exit($exitCode);
} else {
    die("Tui program configuration file not found: " . $argv[1]);
}

